
# Site settings

url: "https://haojunsui.github.io"
baseurl: ""
google-tracking-id: ""
force-https: True

#############
# HTML Head #
#############

lang: "en"
author: "Haojun Sui"
title: "{ Haojun Sui }"
description: "Blog and website of Haojun Sui, blogging mainly for tech. Opinions expressed are mine."
keywords: "haojun, sui, personal, jekyll"
favicon: "/img/favicon.ico"

################
# Header layout #
################

black-favicon: "/img/black-lab-glass.ico"

background-img: "../img/intro-bg.jpg"

##############################
# Dynamic Text on the Header #
##############################

dynamic-typing: True
shuffle: True # Shuffle the lines.
loop: True
loop-count: False # Set False for infinite loop, or set any number for finite loop.
type-speed: 10
start-delay: 200
delete-delay: 5000
lines: # You can add HTML Tags in the Text
  - text: "The lower you fall, the higher you'll fly."
  - text: "Whereâ€™s your will to be weird?"
  - text: "Think different."

me-img: "/img/author.png"

##############################
# Color the browser elements #
##############################
color-browser: "#000000"
apple-status-bar-style: "black"

################
# Web app mode #
################

web-app-mode: True

# Icons for Web App mode

icon-36p: "/img/web-app/icon-36p.png"
icon-48p: "/img/web-app/icon-48p.png"
icon-72p: "/img/web-app/icon-72p.png"
icon-96p: "/img/web-app/icon-96p.png"
icon-144p: "/img/web-app/icon-144p.png"
icon-192p: "/img/web-app/icon-192p.png"

########
# Blog #
########

post-preview-words: 96

paginate: 5

email-share: True
fb-share: True
twitter-share: True
linkedin-share: True
reddit-share: True
google-plus-share: True
tumblr-share: True
pinterest-share: True
pocket-share: True
vkontakte-share: True

disqus-shortname: "haojunsui"

syntax-highlight: True

############
# Timeline #
############

events:
  - image: "/img/timeline/ics.svg"
    date: "November 2015 - June 2016"
    description: "Research Assistant Intern @ Institute for CyberScience, managed campus-wide Apache Hadoop and Spark server, helped university professors resolve technical issues"
  - image: "/img/timeline/beepbeep.png"
    date: "August 2015 - December 2015"
    description: "Beep-Beep Traffic System Builder and Simulator"
  - image: "/img/timeline/duckduckgo.png"
    date: "October 2015 - Today"
    description: "DuckDuckHack Contributors @ <a href=\"https://duckduckgo.com/\" target=\"_blank\">DuckDuckGo</a>, developed <a href=\"https://duckduckgo.com/?q=prime+numbers+between+23+and+56&ia=answer\" target=\"_blank\">Instant Answer - Prime Numbers</a> to display prime numbers between user-given ranges."
  - image: "/img/timeline/pennstate.png"
    date: "September 2013 - May 2017"
    description: "Bachelor studies @ <a href=\"http://eecs.psu.edu\" target=\"_blank\">Department of Electrical Engineering and Computer Science</a> on Computer Science<br>Bachelor studies @ <a href=\"http://www.math.psu.edu\" target=\"_blank\">Department of Mathematics</a> on Mathematics, System Analysis<br>Bachelor studies @ <a href=\"http://stat.psu.edu\" target=\"_blank\">Department of Statistics</a> on Statistics, Applied"

# First image of the Timeline

timeline-img: "/img/author.png"

###########
# Contact #
###########

email: "mr.suihaojun@gmail.com"

################
# Author Blurb #
################

# The author blurb goes underneath blog posts.
# This works best when your author blurb image has a transparent background, or matches your site background color.

# if the author_blurb is not set, then this feature is skipped
author_blurb: "Haojun Sui is an awesome person. He lives in China."
author_blurb_image: "/img/author.png"

##################
# Social Buttons #
##################

social:
  - title: "github"
    url: "https://github.com/haojunsui"
  - title: "bitcoin"
    url: "https://blockchain.info/address/1N1vsqdVYPiPAqwyDhEkzDzAhvVRdiZ44F"
  - title: "rss"
    url: "/feed.xml"

############
# 404 page #
############

404-img: "/img/labtocat.png"

################################################################################

# NB! Tread carefully if you want to change the variables below this point!

# Sections shown in the index page

pages_list:
  About: 'about'
  Blog: 'latest-post'
  Timeline: 'timeline'
  Contact: 'contact'

# Exclusion list from the generated _site

exclude: ["LICENSE", "README.md", "CONTRIBUTING", "CONTRIBUTORS", "scripts"]

# Pagination path

paginate_path: "blog/page:num/"

# Enable minification SASS

sass:
  style: compressed

gems:
  - jekyll-paginate
  - jemoji
